"use client";
import {useMemo,useState} from "react";
import {Shield,GitPullRequest,CheckCircle2,AlertTriangle,Loader2,LockKeyhole,TestTube2,Search,GitBranch,Play,Clock3,XCircle,ChevronRight} from "lucide-react";

type StageKey="github_fetch"|"security_scan"|"patch_generation"|"sandbox_validation"|"approval"|"pr_creation";
const stages:[string,StageKey,any,string][]=[
 ["GitHub fetch","github_fetch",GitBranch,"Connect to the repository and load bounded source files."],
 ["Security scan","security_scan",Search,"Run NEXUS security rules against the fetched files."],
 ["AI patch","patch_generation",Shield,"Generate conservative remediation candidates."],
 ["Sandbox","sandbox_validation",TestTube2,"Run the guarded static safety validation."],
 ["Approval","approval",LockKeyhole,"Review the validated patch before any Git write."],
 ["Pull request","pr_creation",GitPullRequest,"Create branch, commit, and pull request after approval."]
];
const order:StageKey[]=["github_fetch","security_scan","patch_generation","sandbox_validation","approval","pr_creation"];
function labelStatus(state:string|undefined){return state==="success"?"SUCCESS":state==="running"?"RUNNING":state==="failed"?"FAILED":"READY"}
export default function Autopilot(){
 const [owner,setOwner]=useState("Krishna-Gudavalli"),[repo,setRepo]=useState(""),[task,setTask]=useState("Find security issues, generate only safe remediations, validate them, and prepare a pull request."),[p,setP]=useState<any>(null),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState("");
 async function start(){setBusy("start");setError("");try{const r=await fetch("/api/autopilot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({owner,repo,task})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Pipeline failed");setP(d)}catch(e){setError(e instanceof Error?e.message:"Failed")}finally{setBusy(null)}}
 async function runStage(stage:StageKey){if(!p||!(["github_fetch","security_scan","patch_generation","sandbox_validation"] as string[]).includes(stage))return;setBusy(stage);setError("");try{const r=await fetch(`/api/autopilot/${p.id}/stage`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({stage})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Stage failed");setP(d)}catch(e){setError(e instanceof Error?e.message:"Stage failed")}finally{setBusy(null)}}
 async function createPR(){if(!p)return;setBusy("pr_creation");setError("");try{const r=await fetch(`/api/autopilot/${p.id}`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"PR creation failed");setP(d)}catch(e){setError(e instanceof Error?e.message:"Failed")}finally{setBusy(null)}}
 const completed=useMemo(()=>order.filter(k=>p?.stageStates?.[k]==="success").length,[p]);
 return <main className="min-h-screen bg-[#050711] px-4 py-10 text-white md:px-8"><div className="mx-auto max-w-7xl">
  <div className="mb-8"><div className="flex items-center gap-2 text-xs uppercase tracking-[.25em] text-cyan-300"><Shield size={14}/> NEXUS Security Autopilot</div><h1 className="mt-3 text-4xl font-black md:text-6xl">GitHub → Scan → Patch → Sandbox → PR</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-slate-500">Every stage is now a real guarded action. NEXUS pauses before Git writes and requires explicit human approval.</p></div>
  <section className="mb-6 grid gap-4 md:grid-cols-3">
   {[
    ["🔎","Researcher AI","Repository intelligence","Maps repository architecture, attack surface, dependencies and security context."],
    ["🛡️","Security AI","Threat analysis","Correlates scanner evidence, severity, confidence, CWE and OWASP risk."],
    ["🔧","Fixer AI","Remediation engineering","Generates conservative, finding-specific patches and explains the before/after change."]
   ].map(([icon,name,purpose,desc])=><div key={name} className="rounded-3xl border border-white/10 bg-white/[.03] p-5 shadow-xl shadow-black/10">
    <div className="flex items-start justify-between"><div className="text-2xl">{icon}</div><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-[10px] font-black uppercase tracking-widest text-emerald-300">● ONLINE</span></div>
    <h2 className="mt-4 text-lg font-black">{name}</h2><div className="mt-1 text-xs font-semibold text-cyan-300">{purpose}</div><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p>
   </div>)}
  </section>
  <section className="rounded-3xl border border-white/10 bg-white/[.03] p-5 backdrop-blur-xl md:p-7"><div className="grid gap-4 md:grid-cols-2"><label><span className="text-xs text-slate-500">GitHub owner</span><input value={owner} onChange={e=>setOwner(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3"/></label><label><span className="text-xs text-slate-500">Repository</span><input value={repo} onChange={e=>setRepo(e.target.value)} placeholder="your-repo" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3"/></label></div><label className="mt-4 block"><span className="text-xs text-slate-500">Objective</span><textarea value={task} onChange={e=>setTask(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-white/10 bg-black/20 p-3"/></label><button disabled={busy!==null||!repo} onClick={start} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-black text-black disabled:opacity-40">{busy==="start"?<Loader2 className="animate-spin" size={16}/>:<Play size={16}/>} Create guarded pipeline</button>{p&&<span className="ml-4 text-xs text-slate-500">{completed}/4 execution stages complete</span>}</section>
  <div className="my-8 grid gap-3 md:grid-cols-6">{stages.map(([label,key,I,desc],i)=>{const state=p?.stageStates?.[key] as string|undefined;const clickable=!!p&&["github_fetch","security_scan","patch_generation","sandbox_validation"].includes(key);const disabled=busy!==null||(!clickable&&key!=="approval"&&key!=="pr_creation")||state==="running";return <div key={key} className={`relative rounded-2xl border p-4 transition ${state==="success"?"border-emerald-400/30 bg-emerald-400/10":state==="failed"?"border-red-400/30 bg-red-400/10":state==="running"?"border-violet-400/40 bg-violet-400/10":"border-white/10 bg-white/[.02]"}`}><div className="flex items-start justify-between"><I size={18}/>{state==="success"?<CheckCircle2 className="text-emerald-300" size={17}/>:state==="failed"?<XCircle className="text-red-300" size={17}/>:state==="running"?<Loader2 className="animate-spin text-violet-300" size={17}/>:<Clock3 className="text-slate-600" size={17}/>}</div><div className="mt-3 text-xs font-bold">{label}</div><div className="mt-1 text-[11px] leading-4 text-slate-500">{p?.stageDetails?.[key]||desc}</div><div className="mt-3 text-[10px] font-bold tracking-widest text-slate-600">{labelStatus(state)}</div>{clickable&&<button disabled={disabled} onClick={()=>runStage(key)} className="mt-3 inline-flex w-full items-center justify-center gap-1 rounded-lg border border-white/10 bg-white/5 px-2 py-2 text-[11px] font-bold hover:bg-white/10 disabled:cursor-not-allowed disabled:opacity-40">{busy===key?<Loader2 className="animate-spin" size={13}/>:<Play size={13}/>} {state==="success"?"Run again":"Run stage"}</button>}{key==="approval"&&p?.status==="waiting_approval"&&<div className="mt-3 rounded-lg bg-amber-300/10 p-2 text-[11px] text-amber-200">Approval required below.</div>}{key==="pr_creation"&&p?.pullRequest&&<a href={p.pullRequest.url} target="_blank" className="mt-3 flex items-center justify-center gap-1 rounded-lg bg-emerald-300 px-2 py-2 text-[11px] font-black text-black">Open PR <ChevronRight size={13}/></a>}</div>})}</div>
  {error&&<div className="mb-5 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200"><AlertTriangle className="mr-2 inline" size={15}/>{error}</div>}
  {p&&<div className="space-y-5"><section className="grid gap-4 md:grid-cols-5">{[["Security score",`${p.score}/100`],["Risk",p.riskLevel||"CLEAN"],["Findings",p.findings.length],["Patch files",p.changes.length],["Sandbox",p.sandbox.passed?"PASSED":"PENDING"]].map(([a,b])=><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5" key={String(a)}><div className="text-xs text-slate-500">{a}</div><div className="mt-2 text-2xl font-black">{b}</div></div>)}</section>
   {p.autonomyPolicy&&<section className="rounded-3xl border border-violet-400/20 bg-violet-400/5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-violet-200">Risk-based autonomy policy</div><h2 className="mt-2 text-xl font-black">{p.autonomyPolicy.mode}</h2><p className="mt-1 text-sm text-slate-400">{p.autonomyPolicy.message}</p></div><div className="rounded-full border border-white/10 bg-black/20 px-3 py-1.5 text-xs font-bold text-slate-300">Approval: {p.autonomyPolicy.approval}</div></div></section>}
   <section className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-bold">Pipeline log</h2><div className="mt-4 space-y-2">{p.logs.map((x:any,i:number)=><div key={i} className="flex gap-3 text-sm"><CheckCircle2 className="mt-0.5 text-emerald-300" size={15}/><span className="text-slate-400">{x.message}</span></div>)}</div></section>
   {p.findings.length>0&&<section className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-bold">Security findings</h2>{p.findings.map((f:any)=><div key={f.id} className="mt-3 rounded-2xl bg-black/20 p-4"><div className="flex justify-between"><span className="font-mono text-xs text-cyan-300">{f.file}:{f.line}</span><span className="text-xs uppercase text-amber-300">{f.severity}</span></div><div className="mt-2 text-sm">{f.title}</div><p className="mt-1 text-xs text-slate-500">{f.remediation}</p></div>)}</section>}
   {p.changes.length>0&&<section className="rounded-3xl border border-violet-400/20 bg-violet-400/5 p-5"><h2 className="font-bold">🔧 Proposed changes</h2><p className="mt-1 text-xs text-slate-500">Conservative remediation candidates generated by the Fixer AI policy engine. Review the exact diff before approval.</p>{p.changes.map((c:any)=><div key={c.path} className="mt-4 rounded-2xl border border-white/10 bg-black/30 p-4"><div className="font-mono text-sm font-bold text-cyan-300">{c.path}</div><div className="mt-3 rounded-xl border border-white/10 bg-black/40 p-3"><div className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Why</div><pre className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{c.reasons.join("\n")}</pre></div><div className="mt-3 grid gap-3 lg:grid-cols-2"><div><div className="mb-2 text-[10px] font-bold uppercase tracking-widest text-red-300">Before</div><pre className="max-h-72 overflow-auto rounded-xl border border-red-400/10 bg-red-400/5 p-3 text-xs leading-5 text-slate-400">{c.before}</pre></div><div><div className="mb-2 text-[10px] font-bold uppercase tracking-widest text-emerald-300">After</div><pre className="max-h-72 overflow-auto rounded-xl border border-emerald-400/10 bg-emerald-400/5 p-3 text-xs leading-5 text-slate-300">{c.after}</pre></div></div></div>)}</section>}
   {p.stageStates?.sandbox_validation==="success"&&p.changes.length===0&&<section className="rounded-3xl border border-amber-400/20 bg-amber-400/5 p-5"><h2 className="font-bold text-amber-200">Manual remediation required</h2><p className="mt-2 text-sm text-slate-400">NEXUS detected findings, but no conservative automatic patch could be generated. Complex or ambiguous dynamic execution remains manual-review-only. No branch or PR will be created without a concrete safe change.</p></section>}
   {p.status==="waiting_approval"&&p.changes.length>0&&<section className="rounded-3xl border border-amber-400/20 bg-amber-400/5 p-5"><div className="flex gap-3"><LockKeyhole className="text-amber-300"/><div><h2 className="font-bold">Human approval required</h2><p className="mt-1 text-sm text-slate-500">Review the findings and proposed changes before NEXUS creates a branch, commit, or pull request.</p><button onClick={createPR} disabled={busy!==null} className="mt-4 rounded-xl bg-amber-300 px-4 py-2.5 text-sm font-black text-black">{busy==="pr_creation"?"Creating PR…":"Approve & Create Pull Request"}</button></div></div></section>}
   {p.pullRequest&&<section className="rounded-3xl border border-emerald-400/20 bg-emerald-400/5 p-5"><GitPullRequest className="text-emerald-300"/><h2 className="mt-3 text-xl font-black">Pull request created</h2><a className="mt-2 block text-cyan-300 underline" href={p.pullRequest.url} target="_blank">#{p.pullRequest.number} · {p.pullRequest.url}</a></section>}
  </div>}
 </div></main>
}
